### ISSUE TITLE
Check staleness

### ISSUE THREAD

**Issue by marsleezm** [AntidoteDB/antidote#113]
Now the staleness of an update is checked by comparing the time difference between when an update is committed in the original DC and when it is applied. The current staleness is very high (around 10s), which is abnormal. This can be due to the frequency of gossiping protocol in riak_core. It should be checked in detail.

**Comment by cmeiklejohn** [comment]
Can you explain how gossip is used to determine staleness?

**Comment by tcrain** [comment]
I have found on my machine that calling the put on riak core metadata takes several seconds to return (up to 10ish in some cases just for small amounts of data).  This call is asynchronous so the 10 seconds is just to store it on the local node.  Maybe we should find a more lightweight mechanism?

"Can you explain how gossip is used to determine staleness?"
Updates from external DCs cannot be read locally until all local vnodes know that all updates from the external DC have been received up to a time.  This is done by receiving heartbeats from external DCs, then gossiping the heartbeats around the local DC.  The longer it takes to gossip the heartbeats around, the older the data you read.  Check the WP2 report on antidote for a detailed description.

**Comment by albsch** [comment]
We don't use the `riak_core` metadata system anymore, staleness is handled by our `meta_data_sender` module.
