### ISSUE TITLE
Clean way to build and test multiple versions of Antidote

### ISSUE THREAD

**Issue by tcrain** [AntidoteDB/antidote#165]
The plan is to be able to build different versions of Antidote with different consistency or different guarantees.  For example with certification checks, with different types of logging, with different ways of ensuring causality, with full or partial replication, etc...

So we need to have a clean mechanism to do this, allowing us to build and test one or multiple versions at a time.  One possibility is to use the "profiles" provided in rebar3 ( https://www.rebar3.org/docs/profiles ).  But it may take some work to upgrade to rebar3.

An initial approach was provided in pull https://github.com/SyncFree/antidote/pull/153 , but this just creates a different makefile target allowing you to build and test one version at a time (either with or without a certification check).

**Comment by albsch** [comment]
A clean mechanism is introduced in #397 via the application enviroment.
