### ISSUE TITLE
Overlay and dynamic configuration

### ISSUE THREAD

**Issue by cmeiklejohn** [AntidoteDB/antidote#244]
Antidote is currently setup for dynamic configuration: this is done because we want the ability to start the nodes either through Mesos, Docker, Kubernetes, and Google Container Engine, where we want the ability to assign the node name dynamically and required ports dynamically (based on which ports are allocated by the scheduler, or in bridged mode with Docker running multiple containers locally.)

Right now, `config/vm.args` and `config/sys.config` are reading from the environment, which works fantastic for dynamic configuration.  However, Erlang Solutions still wants to build releases using the overlay style -- where variables in `config/sys.config` and `config/vm.args` are replaced by placeholders in `vars.config`.  The unfortunate downside of this strategy is that IP addresses, hostnames, and port numbers need to be known **at the time of building the release** and not **at the time of the deployment** which is not true in environments like Amazon, given arbitrary Elastic IP assignment based on availability, and dynamic port assignment if using bridged networking in virtualized environments.

There's a problem, because while the `vars.config` values are replaced in `sys.config`, the node name in `vm.args` is expected to come from the environment.  We can't use only the overlay style, otherwise, Antidote will not be deployable in a dynamic environment, where port numbers are not known until deployment time -- the overlay style only works when the IP and ports are known at the time of building the release.

What's the proper way to make these work together? cc: @ferd @tsloughter 

```
Protocol 'inet_tcp': invalid node name: longname9249e659-${NODE_NAME}@Christophers-MacBook-Pro.local
```

**Comment by cmeiklejohn** [comment]
I'd argue that we should shy away from any solution where releases are built with machine-specific information in the overlay `vars.config` because then the releases become non-portable and more difficult to debug and manage.  I'd like to see us move towards a situation where a single release can be deployed and at run time, or deployment time, the configuration files are templates, or the configuration is inherited from the environment.

**Comment by albsch** [comment]
With the addition of  `app.src` and `vm.src` this is possible now.
