### ISSUE TITLE
Update Ranch dependency to new major version 2

### ISSUE THREAD

**Issue by albsch** [AntidoteDB/antidote#374]
Ranch version `2.0.0-rc1` is released and introduced breaking changes.

[Migration](https://ninenines.eu/docs/en/ranch/2.0/guide/migrating_from_1.7/) is needed when the final `2.0.0` version is released.

**Comment by albsch** [comment]
Ranch `rc2` is released. No additional API changes so far. Updated branch the [ranch migration branch](https://github.com/AntidoteDB/antidote/tree/374-update-ranch-dependency-to-new-major-version-2) and rebased on master.

**Comment by aryamanpuri** [comment]
@albsch Can I give this a try?

**Comment by bieniusa** [comment]
Go ahead!

**Comment by albsch** [comment]
There's still nothing to do, the ranch major version 2 is not released yet.
I opened a pull request draft to show there is already a branch for this issue ready to be merged whenever ranch 2 is released.

**Comment by albsch** [comment]
[Ranch 2.0.0](https://hex.pm/packages/ranch) was released.

**Comment by albsch** [comment]
When I try to start a release with ranch `2.0.0` I get the following error:

```
2020-08-31T15:21:59.597306+02:00 notice:
    application: antidote
    exited: {{shutdown,
              {failed_to_start_child,antidote_pb_sup,
               {shutdown,
                {failed_to_start_child,ranch_sup,
                 {shutdown,
                  {failed_to_start_child,ranch_server,
                   {badarg,
                    [{ets,match,
                      [ranch_server,{{conns_sup,'$1','$2'},'$3'}],
                      []},
                     {ranch_server,init,1,
                      [{file,
                        "/home/schimpf/git/anti/antidote/_build/default/lib/ranch/src/ranch_server.erl"},
                       {line,176}]},
                     {gen_server,init_it,2,
                      [{file,"gen_server.erl"},{line,374}]},
                     {gen_server,init_it,6,
                      [{file,"gen_server.erl"},{line,342}]},
                     {proc_lib,init_p_do_apply,3,
                      [{file,"proc_lib.erl"},{line,249}]}]}}}}}}},
             {antidote_app,start,[normal,[]]}}
    type: permanent
```

I don't really know why this is not working with `2.0.0` but worked with `2.0.0-rc1`.

**Comment by albsch** [comment]
`ranch_sup` was started by antidote, which should be started by `ranch` itself. It was not an application, moving ranch from `included_applications` to `applications` solved the issue.
