### ISSUE TITLE
Is there current support/plans for subscription to changes on key?

### ISSUE THREAD

**Issue by filipesmedeiros** [AntidoteDB/antidote#418]
Hey!

Just as the title asks. Or also, more generally, is there support for pre/post commit hooks?

If it matters, the use case would be to set up a GraphQL API to Antidote that would support the Subscription type.

Thanks

**Comment by filipesmedeiros** [comment]
Oops, sorry, didn't find the docs page before. My bad,

**Comment by filipesmedeiros** [comment]
Actually sorry again, as my question for subscription still stands. The support for hooks is there. Would that mean that it is possible to implement a subscription system fairly easily?

Something like (JS but read as pseudo-code):
```javascript
function subscribeToKey(bucket_name, key, persistant_connection) {
    register_post_hook(bucketName, (opKey, operation) => {
        if(opKey === key)
            connection.send(key, operation)
    }
}
```

I guess that would mean the cluster itself would have to keep connections alive to all subscribers which seems bad, so is there any other way that I'm not thinking of?

Thanks!

**Comment by bieniusa** [comment]
I am not entirely sure what your use case is - can you give more details?

If you want to use the pre/post-commits, you need to provide the call backs in Erlang and they need to be deployed with the database itself.
Alternatively, you could register with the interDC communication channels (currently ZeroMQ), though this requires at the moment registering with all data centres.

**Comment by filipesmedeiros** [comment]
Hey,

> I am not entirely sure what your use case is - can you give more details?

Sure! In short (let me know if you want me to go even deeper) having Subscription logic would allow real-time applications to be developed.

> If you want to use the pre/post-commits, you need to provide the call backs in Erlang and they need to be deployed with the database itself.

Right! I guess you can always prepare an endpoint before deploying, use that as the hook and change that. So right now the main point is (I think): it would be nice to be able to register hooks during the lifetime of Antidote, and not just before it's deployed.

> Alternatively, you could register with the interDC communication channels (currently ZeroMQ), though this requires at the moment registering with all data centres.

I see, that could be a way. Does Antidote (or Riak?) expose the ZeroMQ config (ports and such) in a nice way for use after deployment? Can that part be configured? I can't find it in the normal config files.

Thanks!
