### ISSUE TITLE
Last release 2 years old

### ISSUE THREAD

**Issue by tensor-programming** [AntidoteDB/antidote#495]
A project that I am working on is considering using Antidote in prod.  One of our team pointed out that the last release happened nearly 2 years ago despite the fact that the repo is still very much under active development.  I am wondering if there is a reason for this and if we should be using dev in our k8s cluster or should we be building with your `0.2.2` release?

**Comment by bieniusa** [comment]
To be honest, Antidote has a few issues at the moment that makes it a bit (too?) flaky for usage in production. The major problems right now are the interDC communication (especially under high load and reconnection) and the interplay of cache and file storage. Happy to discuss in more detail, if you are interested.
We continue to work on the code, and have an approximate roadmap regarding the issues.  

If you want to deploy for testing etc. I suggest using the latest version on Master for the moment. Next release should be out in the next 2 weeks.

**Comment by felipevalerio** [comment]
Hi, I just wanted to know. Is the project in active development?
